import { chromium } from 'playwright';
const browser = await chromium.launch({ executablePath: '/home/z/.cache/ms-playwright/chromium-1234/chrome-linux64/chrome' });
const page = await browser.newPage();
const bad = [];
page.on('response', r => { if (r.status() >= 400) bad.push(r.status() + ' ' + r.url()); });
page.on('console', m => { if (m.type() === 'error') console.log('CONSOLE:', m.text().slice(0,200)); });
await page.goto('http://localhost:3000/', { waitUntil: 'networkidle' });
await page.waitForTimeout(3000);
console.log('=== 4xx/5xx responses ===');
bad.forEach(x => console.log(x));
await browser.close();
